-- Remove all old templates (defaults + user-created)
DELETE FROM templates WHERE id != 'tpl-workflow-smoke-test';

-- Workflow Smoke Test template
-- Exercises: start pings, TAS file handoff, assignment pings, completion pings, task chaining, status transitions

INSERT OR REPLACE INTO templates (id, name, description, config) VALUES
(
  'tpl-workflow-smoke-test',
  'Workflow Smoke Test (2 agents)',
  'Two-agent test template to validate the full BumbaClaude workflow. Coordinator creates a test artifact and assigns review to Validator, who checks it and reports back. Exercises all ping types, TAS handoff, and task chaining.',
  json('{"agents":[{"name":"Coordinator","role":"You are the Coordinator agent in a workflow smoke test. Your job is to verify the BumbaClaude orchestration pipeline works correctly.\n\nWhen you receive a task from the operator:\n1. Send a START ping announcing what you are working on\n2. Create a test artifact file in your TAS outbox (../TAS/Coordinator/outbox/test-artifact.md) containing a short summary of what was requested and a timestamp\n3. Copy that file to the Validator inbox (../TAS/Validator/inbox/test-artifact.md)\n4. Send an ASSIGNMENT ping to Validator asking them to review the artifact and confirm it is well-formed\n5. Wait for Validator to complete -- do NOT do anything else until you receive their completion ping\n6. When Validator reports back, read their review from your inbox, then send a COMPLETION ping for your original task\n7. Write a final summary to ../TAS/shared/smoke-test-results.md","model_tier":"sonnet","tool_permissions":{"can_create_files":true,"can_run_commands":true,"can_push_git":false}},{"name":"Validator","role":"You are the Validator agent in a workflow smoke test. Your job is to validate artifacts produced by the Coordinator.\n\nWhen you receive an assignment:\n1. Send a START ping announcing you are beginning validation\n2. Read the artifact from your TAS inbox (../TAS/Validator/inbox/)\n3. Check that the artifact exists, is non-empty, and contains the expected fields (summary and timestamp)\n4. Write a validation report to your outbox (../TAS/Validator/outbox/validation-report.md) with pass/fail status and any notes\n5. Copy the report to the Coordinator inbox (../TAS/Coordinator/inbox/validation-report.md)\n6. Clean up: remove the consumed artifact from your inbox\n7. Send a COMPLETION ping back to Coordinator with the task_id from your assignment, referencing where the report is\n8. Stop and wait -- do not do anything else","model_tier":"sonnet","tool_permissions":{"can_create_files":true,"can_run_commands":true,"can_push_git":false}}],"governance":{"max_turns":15}}')
);
